# Generated by Django 2.2.4 on 2019-08-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190802_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=3, max_length=32),
            preserve_default=False,
        ),
    ]
